## BIOS
alias bios='sudo dmidecode -s bios-version'
alias rebios='sudo systemctl reboot -i --firmware-setup'

## System info
alias kernel='uname -r'
alias os='cat /etc/os-release'
# Fastfetch
if [[ "$(cat /sys/devices/virtual/dmi/id/product_version 2>/dev/null)" == ThinkPad* ]]; then
	alias ff='fastfetch -l ~/.config/fastfetch/thinkpad-v.txt'
else
	alias ff='fastfetch'
fi

## System update
alias sysupdate='sys-update'

## Shortcuts
alias cdgh='cd ~/Code/GitHub && ls'
alias chmodx='chmod +x'
alias docker='podman'
